services:
  vortex-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.server:app --host 0.0.0.0 --port 8000 --reload
